import express, { Application } from "express";
import dotenv from "dotenv";
import { User } from "./user/User";
import { Balance } from "./models/balance";
import { UserInfo } from "./models/userInfo";

const app: Application = express();
const port = 3000;
// const key: string = await process.env.COINDCX_API_KEY?.toString() || '';
// const secret: string = await process.env.COINDCX_SECRET?.toString() || '';
dotenv.config();
app.get("/", async (_, res) => {
    try {

        const user: User = new User();
        const resData: UserInfo = await user.UserInfo();
        res.send(resData);
    } catch (error) {
        res.status(500).send(error);
    }
});
app.get("/balance", async (_, res) => {
    try {
        const user: User = new User();
        const resData: Balance[] = await user.UserBalance();
        res.send(resData.filter(item => { return parseFloat(item.balance) !== 0 }));
    } catch (error) {
        res.status(500).send(error);
    }
});

app.listen(port, () => {
    return console.log(`server is listening on http://localhost:${port}`);
});
; (async function () {

}()
);

// Generated by https://quicktype.io
